# Copyright 2021 Ke Fan <litesky@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: v1
data:
  kubeconfig: |-
    #k8s 访问配置文件
  peitho.yml: |-
    peitho:
      imageMode: delivery #registry of delivery
      pullerAccessAddress: http://peitho:8080/tar
      pullerImage: x.x.x.x:8099/platform/puller-amd64:v-2-g5cada04
    k8s:
      namespace: fabric #命名空间
      kubeconfig: /root/kube/kubeconfig #k8s访问配置文件
      dns: #如果chaincode 和 peer不在同一个环境的情况下，需要配置peer地址的解析
        - 127.0.0.1:peer0.org1.example.com
        - 127.0.0.1:peer1.org1.example.com
        - 127.0.0.1:peer0.org2.example.com
        - 127.0.0.1:peer1.org2.example.com
    docker:
      endpoint: unix:///host/var/run/docker.sock # docker的端点
      registry: #镜像仓库相关
        server-address: #仓库地址
          xxx.xxx.xxx.xxx:xxxx
        project: #项目名
          chaincode
        email: #邮箱
          litesky@foxmail.com
        username: #用户名
          admin
        password: #密码
          harbor
    log:
      name: peitho # Logger的名字
      development: true # 是否是开发模式。如果是开发模式，会对DPanicLevel进行堆栈跟踪。
      level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
      format: console # 支持的日志输出格式，目前支持console和json两种。console其实就是text格式。
      enable-color: true # 是否开启颜色输出，true:是，false:否
      disable-caller: true # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
      disable-stacktrace: false # 是否再panic及以上级别禁止打印堆栈信息
kind: ConfigMap
metadata:
  name: peitho-configmap
  namespace: fabric
